name: 5min Commit

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "auto commit"

      - name: Push
        run: |
          git push
